### ISSUE TITLE
LICENSE and USAGE

### ISSUE THREAD

**Issue by christopher-r-serrano** [bedbad/justpyplot#1]
I would like to use the project, but without a license I cannot do so in the workplace.

**Comment by bedbad** [comment]
Sorry, fixed. I manage to many small repos in a monorepo infra and miss stuff like that sometimes when publishing it outside.

As you do use it please provide real use case feedback. It allows to opensource, update and respond to issues much intensively when use or need is apparent

**Comment by bedbad** [comment]
I manage to many small repos in a monorepo infra and miss stuff like that sometimes when publishing it outside.

The License for the code released is MIT - it is really basic seed-level code that was written in day a half by one person as a side-project unrelated to the main line of work to demonstrate some inadequacy of matplotlib.

There's are much more robust versions in work now. 
Since you worry about license at work you have a real use case -  it would be nice to communicate what you want and why so that you and others can actually benefit from a more work ready code and developers get some appreciation.

The prod version release and license decision is not made yet.
